// export const CsvHeaders = [
//   {
//     label: "Serial No.",
//     key: "sNo",
//   },
//   {
//     label: "Name",
//     key: "firstName",
//   },
//   {
//     label: "Email",
//     key: "email",
//   },
//   {
//     label: "Department",
//     key: "departmentTitle",
//   },
//   {
//     label: "User Type",
//     key: "userTypeTitle",
//   },
//   {
//     label: "Organization",
//     key: "OrganizationName",
//   },
// ];
// export const Columns = [
//   {
//     title: "Name",
//     dataIndex: "firstName",
//     key: "firstName",
//     sorter: (a, b) =>
//       a?.firstName?.toLowerCase()?.localeCompare(b.firstName?.toLowerCase()),
//   },
//   {
//     title: "Email",
//     dataIndex: "email",
//     key: "email",
//     sorter: (a, b) => a?.email?.toLowerCase() === b?.email?.toLowerCase(),
//   },
//   {
//     title: "Department",
//     dataIndex: "departmentTitle",
//     key: "departmentTitle",
//     sorter: (a, b) =>
//       a?.departmentTitle
//         ?.toLowerCase()
//         ?.localeCompare(b.departmentTitle?.toLowerCase()),
//   },
//   {
//     title: "User Type",
//     dataIndex: "userTypeTitle",
//     key: "userTypeTitle",
//     sorter: (a, b) =>
//       a?.userTypeTitle
//         ?.toLowerCase()
//         ?.localeCompare(b?.userTypeTitle?.toLowerCase()),
//   },
//   {
//     title: "Organization",
//     dataIndex: "OrganizationName",
//     sorter: (a, b) =>
//       a?.OrganizationName?.toLowerCase()?.localeCompare(
//         b.OrganizationName?.toLowerCase()
//       ),
//     key: "OrganizationName",
//   },
// ];
export const FormDataSetting = {
  submit_url: "/api/user/create",
  form: [
    {
      mainType: "deals",
      id: "1",
      type: "text",
      required: true,
      isUpdate: true,
      label: "Title",
      name: "title",
      placeHolder: "Enter Title",
      value: "",
      errorMessage: "Enter Valid Title !",
      regex: /^[a-zA-z]+([\\s][a-zA-Z]+)*$/,
    },
    {
      mainType: "deals",
      id: "2",
      type: "text",
      required: true,
      isUpdate: true,
      name: "description",
      label: "Description",
      popupText: "",
      helpNote: "",
      placeHolder: "Enter Description",
      errorMessage: "Enter valid Description",
      regex: /^[a-zA-z]+([\\s][a-zA-Z]+)*$/,
      value: "",
    },
    {
      mainType: "deals",
      id: "3",
      type: "number",
      required: true,
      isUpdate: true,
      name: "price",
      label: "Price",
      popupText: "",
      helpNote: "",
      placeHolder: "Enter Price",
      errorMessage: "Enter valid Price",
      regex: /^[a-zA-z]+([\\s][a-zA-Z]+)*$/,
      value: "",
    },
    {
      mainType: "deals",
      id: "4",
      type: "Select",
      required: true,
      isUpdate: true,
      name: "categoryId",
      label: "Category",
      popupText: "",
      helpNote: "",
      placeHolder: "Select Category",
      errorMessage: "Please select an option.",
      regex: /./,
      value: "",
    },
    {
      mainType: "deals",
      id: "5",
      type: "Select",
      required: true,
      isUpdate: true,
      name: "size",
      label: "Size",
      popupText: "",
      helpNote: "",

      options: [
        { value: "large", label: "Large" },
        { value: "medium", label: "Medium" },
        { value: "small", label: "Small" },
      ],

      placeHolder: "Select Size",
      errorMessage: "Enter Valid Size",
      regex: /^[a-zA-z]+([\\s][a-zA-Z]+)*$/,
      value: "",
    },
    {
      mainType: "deals",
      id: "6",
      type: "Select",
      required: true,
      isUpdate: true,
      name: "type",
      label: "Type",
      popupText: "",
      helpNote: "",

      options: [
        { value: "deals", label: "Deals" },
        { value: "menu", label: "Menu" },
      ],

      placeHolder: "Select Type",
      errorMessage: "Enter Valid Type",
      regex: /^[a-zA-z]+([\\s][a-zA-Z]+)*$/,
      value: "",
    },
    {
      mainType: "deals",
      id: "7",
      type: "file",
      required: true,
      isUpdate: true,
      name: "image",
      label: "Image",
      popupText: "",
      helpNote: "",
      errorMessage: "Enter valid Image",
      regex: /^[a-zA-z]+([\\s][a-zA-Z]+)*$/,
      value: "",
    },
    {
      mainType: "options",
      id: "8",
      type: "text",
      required: true,
      isUpdate: true,
      name: "value",
      label: "Name",
      popupText: "",
      helpNote: "",
      placeHolder: "Enter Value",
      errorMessage: "Enter valid Value",
      regex: /^[a-zA-z]+([\\s][a-zA-Z]+)*$/,
      value: "",
    },
    {
      mainType: "options",
      id: "9",
      type: "text",
      required: true,
      isUpdate: true,
      name: "label",
      label: "Label",
      popupText: "",
      helpNote: "",
      placeHolder: "Enter Label",
      errorMessage: "Enter valid Label",
      regex: /^[a-zA-z]+([\\s][a-zA-Z]+)*$/,
      value: "",
    },
    // {
    //   id: "3",
    //   type: "text",
    //   required: true,
    //   isUpdate: false,
    //   name: "email",
    //   label: "Official Email",
    //   popupText: "",
    //   helpNote: "",
    //   placeHolder: "Enter Official Email",
    //   errorMessage: "Enter valid Email",
    //   regex: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
    //   value: "",
    // },
    // {
    //   id: "4",
    //   type: "password",
    //   required: false,
    //   isUpdate: false,
    //   label: "password",
    //   name: "password",
    //   popupText: "",
    //   errorMessage: "Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character",
    //   placeHolder: "Enter New Password",
    //   helpNote: "",
    //   value: "",
    //   regex: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.+!@#\$%\^&\*])/,
    // },
    // {
    //   id: "5",
    //   type: "Select",
    //   required: true,
    //   isUpdate: false,
    //   label: "Select City",
    //   name: "select",
    //   popupText: "",
    //   errorMessage: "Please select an option.",
    //   placeHolder: "Select",
    //   helpNote: "",
    //   value: {value:'',label:''},
    //   regex: /./ ,
    // },
  ],
};
